#Application URL
url=https://yethiprod.tenjinonline.com/signin

#Browser Type
browser=chrome

#Credentails
username=Ayn.uddin@yethi.co.in
password=Welcome@2020

#Implicit wait (int sec)
implicitWait=5